### ISSUE TITLE
Issues after upgrading to v4

### ISSUE THREAD

**Issue by evoyy** [dlepaux/realtime-bpm-analyzer#72]
After upgrading to v4, the data returned during continuous analysis is inconsistent with the documentation.

This does not work:

````javascript
realtimeAnalyzerNode.port.onmessage = (event) => {
  if (event.data.message === 'BPM_STABLE') {
    console.log('BPM_STABLE', event.data.result);
  }
};
`````
Dumping the data to the console I see this:

![Screenshot 2024-02-20 024845](https://github.com/dlepaux/realtime-bpm-analyzer/assets/1623890/cac7a476-28b7-434b-875c-eca90f3a4a2a)

So I figured that to get the stable BPM it should be:

````javascript
realtimeAnalyzerNode.port.onmessage = (event) => {
  if (event.data.message === 'BPM_STABLE') {
    console.log('BPM_STABLE', event.data.data.bpm[0].tempo);
  }
};
`````

Also I noticed that you no longer provide a high pass filter. I assume this is no longer required for analysis? I assume not, as the analyzer still works fine for me.

**Comment by dlepaux** [comment]
Thank you for your return, I will update the doc accordingly.

About the high pass filter. I removed it because it is not necessary. I've done some tooling to test a bunch of audiofiles, and it appears that the current implementation doesn't need to use a high pass filter.
I'm working on improvements to make the algorithm as precise as possible.

**Comment by evoyy** [comment]
Thanks for the clarification, and for all your work on this. Please close this issue whenever you like.

**Comment by dlepaux** [comment]
Thank you for your contribution I've updated the documentation accordingly.
